[tool.poetry]
name = "mini-top"
version = "0.1.0"
description = ""
authors = ["Gabriele N. Tornetta <phoenix1987@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
austin-tui = "^0.1.3"
psutil = "^5.7.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
